server:
  port: 8889
  enable-self-preservation: false
  eviction-interval-timer-in-ms: 4000

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/